web/router.ex
defmodule Eventrist.Router do
  use Eventrist.Web, :router
  import Eventrist.Session

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :user_data do
    plug :require_login
  end

  pipeline :feed do
    plug :accepts, ["text/calendar"]
  end

  scope "/", Eventrist do
    pipe_through :browser

    get  "/login",  RegistrationController, :login
    post "/login",  RegistrationController, :do_login
    get  "/signup", RegistrationController, :signup
    post "/signup", RegistrationController, :do_signup
    get  "/logout", RegistrationController, :logout

    get "/loaderio-88ec75cd570841f1ac0b26dfd6efbb93", LoaderioController, :verify

    # main page is info about the app
    get "/", RootController, :index
  end

  scope "/", Eventrist do
    pipe_through :feed
    get "/users/:user_id/feed.ical", FeedController, :feed
  end

  scope "/", Eventrist do
    pipe_through [:browser, :user_data]

    # Next recommended event for logged in user
    get "/events/next", EventsController, :next_event
    # Get all events that the logged in user has ignored
    get "/events/ignored", EventsController, :ignored
    # Save an event for the logged in user, either ignoring or adding it
    post "/events/:id/save", EventsController, :save_event
    # Get all events for the logged in user and show details about a specific event
    resources "/events", EventsController, only: [:index, :show]
  end

  defp require_login(conn, _) do
    case !logged_in?(conn) do
      true  -> redirect(conn, to: Eventrist.Router.Helpers.registration_path(conn, :login)) |> halt
      _     -> conn
    end
  end

  #pipeline :review_checks do
  #  plug :ensure_authenticated_user
  #  plug :ensure_user_owns_review
  #end
  #scope "/reviews", Eventrist do
  #  pipe_through :review_checks
  #  resources "reviews", ReviewController
  #end

  # see info for a particular user and see the events for that user
  #resources "users", UserController, only: [:show] do
  #  resources "events", EventsController, only: [:index, :create, :delete]
  #  resources "tags", TagsController, only: [:index]
  #end

  # see organisers and their events
  #resources "organisers", OrganisersController, only: [:index, :show] do
  #  resources "tags", TagsController, only: [:index]
  #  resources "events", EventsController, only: [:index]
  #end
end

web/models/event.ex
defmodule Eventrist.Event do
  use Eventrist.Web, :model

  schema "events" do
    field :source, :string
    field :source_id, :string
    field :title, :string
    field :description, :string
    field :link, :string
    field :organiser, :string
    field :cancelled, :boolean
    field :start_time, Ecto.DateTime
    field :end_time, Ecto.DateTime
    belongs_to :venue, Eventrist.Venue
    has_many :user_events, Eventrist.UserEvent
    has_many :saved_by_users, through: [:user_events, :event]
    timestamps
  end

  @required_fields ~w(source source_id title description link organiser cancelled start_time venue_id)
  @optional_fields ~w(end_time)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:source_id, name: :events_source_source_id_index)
  end

  def find_by_organiser_start_time_and_city(organiser, start_time, city) do
    from event in Eventrist.Event,
    join: venue in Eventrist.Venue,
      on: event.venue_id == venue.id
        and venue.city == ^city
        and event.organiser == ^organiser
        and event.start_time == ^start_time,
        select: event
  end
end

web/controllers/events_controller.ex
defmodule Eventrist.EventsController do
  use Eventrist.Web, :controller

  @months_before_event 1

  def user_events(user_id) do
    user_events(user_id, "added")
  end

  def user_events(user_id, status) do
    now = Ecto.DateTime.utc

    from event in Eventrist.Event,
    join: saved in Eventrist.UserEvent,
      on: saved.status == ^status
        and saved.user_id == ^user_id
        and saved.event_id == event.id
        and event.start_time > ^now
        and not event.cancelled,
    select: event,
    order_by: [asc: event.start_time]
  end

  # get saved events for a user
  def index(conn, _params) do
    user_id = get_session(conn, :current_user)
    q = user_events(user_id)
    events = Eventrist.Repo.all(q)

    # okay to lookup this key here by user ID, as the user has to be
    # logged in to access this route
    calendar_key =
      case Eventrist.Repo.get_by(Eventrist.CalendarKey, user_id: user_id) do
        nil -> Eventrist.CalendarKey.create!(user_id)
        x   -> x
      end

    render conn, events: events, user_id: user_id, calendar_key: calendar_key.key
  end

  def ignored(conn, _params) do
    user_id = get_session(conn, :current_user)
    q = user_events(user_id, "ignored")
    events = Eventrist.Repo.all(q)

    render conn, events: events, user_id: user_id
  end

  def show(conn, params) do
    user_id = get_session(conn, :current_user)

    user_event_status = Eventrist.Repo.one(
      from user_event in Eventrist.UserEvent,
      where: user_event.user_id == ^user_id and user_event.event_id == ^params["id"],
      select: user_event.status
    )

    event = Eventrist.Repo.get!(Eventrist.Event, params["id"])
    |> Eventrist.Repo.preload(:venue)

    render conn, event: event, saved_status: user_event_status
  end

  def next_event(conn, _params) do
    user_id = get_session(conn, :current_user)
    now = Ecto.DateTime.utc

    upcoming_events =
      from event in Eventrist.Event,
      where: event.start_time > ^now
      and event.start_time < datetime_add(^now, @months_before_event, "month")
      and not event.cancelled

    not_saved_events =
      from event in upcoming_events,
        left_join: user_event in Eventrist.UserEvent,
        on: user_event.user_id == ^user_id and user_event.event_id == event.id,
       where: is_nil(user_event.id),
       select: event,
       order_by: [asc: event.start_time],
       limit: 1,
       preload: [:venue]

    event = Eventrist.Repo.one(not_saved_events)
    if event == nil do
      render conn, "no_next.html"
    else
      # want user to be able to copy link, so redirect instead of rendering content directly
      redirect conn, to: events_path(conn, :show, event.id)
    end
  end

  def save_event(conn, params) do
    event_id = params["id"]
    user_id = get_session(conn, :current_user)
    status = params["action"]
    save_event(event_id, user_id, status)

    path = case params["redirect_path"] do
      nil -> events_path(conn, :next_event)
      p   -> p
    end

    redirect conn, to: path
  end

  defp save_event(event_id, user_id, status) do
    event_changes = %{
      event_id:   event_id,
      user_id:    user_id,
      status:     status
    }
    case Eventrist.Repo.get_by(Eventrist.UserEvent, user_id: user_id, event_id: event_id) do
      nil ->
        changeset = Eventrist.UserEvent.changeset(%Eventrist.UserEvent{}, event_changes)
        Eventrist.Repo.insert!(changeset)
      x   ->
        changeset = Eventrist.UserEvent.changeset(x, event_changes)
        Eventrist.Repo.update!(changeset)
    end
  end
end

web/views/events_view.ex
defmodule Eventrist.EventsView do
  use Eventrist.Web, :view

  def action_text(:add) do
    "✓"
  end

  def action_text(:ignore) do
    "✗"
  end

  def action_path(:add, conn, event, redirect_path) do
    events_path(conn, :save_event, event.id, action: "added", redirect_path: redirect_path)
  end

  def action_path(:ignore, conn, event, redirect_path) do
    events_path(conn, :save_event, event.id, action: "ignored", redirect_path: redirect_path)
  end

  def is_in_past(time) do
    now = :calendar.universal_time
    dt = Ecto.DateTime.to_erl time

    now_secs = :calendar.datetime_to_gregorian_seconds now
    time_secs = :calendar.datetime_to_gregorian_seconds dt

    now_secs >= time_secs
  end

  def format_datetime(datetime) do
    {date, time} = Ecto.DateTime.to_erl datetime
    "#{format_erl_time time} on #{format_erl_date date}"
  end

  def format_from_to(from, to) do
    if to == nil do
      format_datetime from
    else
      {from_date, from_time} = Ecto.DateTime.to_erl from
      {to_date, to_time} = Ecto.DateTime.to_erl to
      if from_date == to_date do
        "#{format_erl_time from_time} - #{format_erl_time to_time} on #{format_erl_date to_date}"
      else
        "#{format_erl_time from_time} on #{format_erl_date from_date} - #{format_erl_time to_time} on #{format_erl_date to_date}"
      end
    end
  end

  defp format_erl_date({_year, month, day} = date) do
    dow = case :calendar.day_of_the_week date do
      1 -> "Mon"
      2 -> "Tues"
      3 -> "Wed"
      4 -> "Thurs"
      5 -> "Fri"
      6 -> "Sat"
      7 -> "Sun"
    end
    "#{dow}, #{format_day(day)} #{format_month(month)}"
  end

  defp format_erl_time({hours, mins, _secs}) do
    "#{format_digits hours}:#{format_digits mins}"
  end

  defp format_digits(digits) do
    case digits do
      x when x < 10 -> "0#{x}"
      x -> "#{x}"
    end
  end

  defp format_day(day) do
    units = case rem(day, 10) do
      1 -> "1st"
      2 -> "2nd"
      3 -> "3rd"
      x -> "#{x}th"
    end
    case div(day, 10) do
      0 -> "#{units}"
      1 -> "#{day}th"
      x -> "#{x}#{units}"
    end
  end

  defp format_month(month) do
    case month do
      1  -> "January"
      2  -> "February"
      3  -> "March"
      4  -> "April"
      5  -> "May"
      6  -> "June"
      7  -> "July"
      8  -> "August"
      9  -> "September"
      10 -> "October"
      11 -> "November"
      12 -> "December"
    end
  end

  def format_time_from_now(time) do
    {now_date, now_time} = :calendar.universal_time
    {time_date, time_time} = Ecto.DateTime.to_erl time

    now_days = :calendar.date_to_gregorian_days now_date
    time_days = :calendar.date_to_gregorian_days time_date

    now_secs = :calendar.time_to_seconds now_time
    time_secs = :calendar.time_to_seconds time_time

    case time_days - now_days do
      1                   -> "Starts tomorrow"
      -1                  -> "Started yesterday"
      days when days > 0  -> "Starts in #{days} days"
      days when days < 0  -> "Started #{-days} days ago"
      0                   ->
        case time_diff(time_secs, now_secs) do
          {0, 0, 0}                                       -> "Starting now"
          {1, mins, _} when mins == 30                    -> "Starts in an hour and a half"
          {1, mins, _} when mins < 30                     -> "Starts in about an hour"
          {-1, mins, _} when mins == -30                  -> "Started an hour and a half ago"
          {-1, mins, _} when mins > -30                   -> "Started about an hour ago"
          {hours, mins, _} when hours > 0 and mins > 30   -> "Starts in about #{hours+1} hours"
          {hours, mins, _} when hours < 0 and mins < -30  -> "Started about #{(-hours)+1} hours ago"
          {hours, mins, _} when hours > 0 and mins < 30   -> "Starts in about #{hours} hours"
          {hours, mins, _} when hours < 0 and mins > -30  -> "Started about #{-hours} hours ago"
          {hours, mins, _} when hours > 0 and mins == 30  -> "Starts in #{hours} and a half hours"
          {hours, mins, _} when hours < 0 and mins == -30 -> "Started #{-hours} and a half hours ago"
          {0, 1, _}                                       -> "Starts in a minute"
          {0, -1, _}                                      -> "Started a minute ago"
          {0, 30, _}                                      -> "Starts in half an hour"
          {0, -30, _}                                     -> "Started half an hour ago"
          {0, mins, _} when mins > 0                      -> "Starts in #{mins} minutes"
          {0, mins, _} when mins < 0                      -> "Started #{-mins} minutes ago"
          {0, 0, 1}                                       -> "Starts in a second"
          {0, 0, -1}                                      -> "Started a second ago"
          {0, 0, secs} when secs > 0                      -> "Starts in #{secs} seconds"
          {0, 0, secs} when secs < 0                      -> "Started #{-secs} seconds ago"
        end
    end
  end

  defp time_diff(a, b) do
    diff = a - b

    hours = div diff, (60 * 60)
    rem_hours = rem diff, (60 * 60)

    mins = div rem_hours, 60
    rem_mins = rem rem_hours, 60

    {hours, mins, rem_mins}
  end
end

web/templates/events/events_list.html.eex
<div class="event-list">
  <%= for event <- @events do %>
    <div class="event-item">
      <h4><%= link event.title, to: events_path(@conn, :show, event.id) %></h4>
      <div class="event-details">
        <p><%= format_from_to event.start_time, event.end_time %></p>
        <p>(<%= format_time_from_now event.start_time %>)</p>
      </div>
      <div class="item-actions">
        <%= link action_text(@action), to: action_path(@action, @conn, event, @action_redirect_path), method: :post%>
      </div>
    </div>
  <% end %>
</div>

web/templates/events/ignored.html.eex
<%= if length(@events) == 0 do %>
<div class="no-recs">
  <p>No events ignored yet.</p>
  <p>Take a look at your <%= link "recommended events", to: events_path(@conn, :next_event) %>.</p>
  <p>Looking for your <%= link "saved events", to: events_path(@conn, :index) %>?</p>
</div>
<% else %>
<div class="event-list-container">
  <%= render Eventrist.EventsView, "events_list.html", conn: @conn, events: @events, action: :add, action_redirect_path: events_path(@conn, :ignored) %>
  <h4 class="other-events-link">
    Looking for your <%= link "saved events", to: events_path(@conn, :index) %>?
  </h4>
</div>
<% end %>

web/templates/events/index.html.eex
<%= if length(@events) == 0 do %>
<div class="no-recs">
  <p>No events saved yet.</p>
  <p>Take a look at your <%= link "recommended events", to: events_path(@conn, :next_event) %>.</p>
  <p>Looking for your <%= link "ignored events", to: events_path(@conn, :ignored) %>?</p>
</div>
<% else %>
<div class="event-list-container">
  <div class="copy-link">
    <p class="link-label">Link for calendar import:</p>
    <p><%= link feed_url(@conn, :feed, @user_id, key: @calendar_key), to: feed_url(@conn, :feed, @user_id, key: @calendar_key), id: "calendarlink", target: "_blank" %></p>
    <button id="copy" class="btn btn-primary" data-clipboard-target="#calendarlink">
        <img src="images/clippy.svg" alt="Copy to clipboard">
    </button>
  </div>
  <script>
  (function(){
    var element = document.getElementById("copy");
    var text = element.innerHTML;
    var clipboard = new Clipboard("#copy");
    clipboard.on('success', function(e) {
        e.clearSelection();
        element.innerHTML = "Copied!";
        setTimeout(function() {
          element.innerHTML = text;
        }, 1000)
    });

    clipboard.on('error', function(e) {
      element.innerHTML = "Failed to copy :(";
      setTimeout(function() {
        element.innerHTML = text;
      }, 3000)
    });
  })();
  </script>

  <div class="event-list">
    <%= render Eventrist.EventsView, "events_list.html", conn: @conn, events: @events, action: :ignore, action_redirect_path: events_path(@conn, :index) %>
    <h4 class="other-events-link">
      Looking for your <%= link "ignored events", to: events_path(@conn, :ignored) %>?
    </h4>
  </div>
</div>
<% end %>

web/templates/events/no_next.html.eex
<div class="no-recs">
  <p>No more recommendations, check back soon!</p>
  <p>Take a look at your <%= link "saved events", to: events_path(@conn, :index) %>.</p>
</div>

web/templates/events/show.html.eex
<script>
  function initialize() {
    var event_pos = {lat: <%= @event.venue.lat %>, lng: <%= @event.venue.lng %>};

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: event_pos,
      streetViewControlOptions: {
        position: google.maps.ControlPosition.TOP_RIGHT
      },
      zoomControlOptions: {
        position: google.maps.ControlPosition.TOP_RIGHT
      },
      mapTypeControl: true
    });

    map.addListener('click', closeWindow);

    var marker = new google.maps.Marker({
      position: event_pos,
      map: map,
      title: "<%= @event.venue.name %>"
    });

    marker.addListener('click', function() {
      var elem = document.getElementById("venue-window");
      elem.style.display = "initial";
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);

  function closeWindow() {
    var elem = document.getElementById("venue-window");
    elem.style.display = "none";
  }
</script>
<div>
  <div id="map"></div>
  <div id="venue-window" style="display: none;">
    <div class="venue-container">
      <div class="venue-content">
        <h4><%= @event.venue.name %></h4>
        <p>
          <%= if @event.venue.address, do: raw(String.replace(@event.venue.address, "\r\n", ", ") |> String.replace(",,", ",")) %>
        </p>
        <p>
          <a href='http://maps.google.com/?q=<%= @event.venue.lat %>,<%= @event.venue.lng %>' target='_blank'>Open in Google Maps</a>
        </p>
      </div>
      <button onclick="closeWindow()">x</button>
    </div>
  </div>
  <div class="event_details">
    <div class="event_container">
      <div class="event_content">
        <h1>
          <%= link @event.title, to: @event.link, target: "_blank" %>
        </h1>
        <div class="event_header">
          <h3><%= @event.organiser %></h3>
          <h5><%= format_from_to @event.start_time, @event.end_time %></h5>
          <h5>(<%= format_time_from_now @event.start_time %>)</h5>
        </div>
        <p><%= raw String.replace(@event.description, "\n", "<br>") %></p>
      </div>
      <div class="event_actions">
        <%= if not is_in_past(@event.start_time) do %>
          <%= case @saved_status do %>
            <% "added" -> %>
              <%= link "✗ Ignore", to: events_path(@conn, :save_event, @event.id, action: "ignored", redirect_path: events_path(@conn, :index)), method: :post, class: "action-btn single" %>
            <% "ignored" -> %>
              <%= link "✓ Save", to: events_path(@conn, :save_event, @event.id, action: "added", redirect_path: events_path(@conn, :ignored)), method: :post, class: "action-btn single" %>
            <% nil -> %>
              <%= link "✗ Ignore", to: events_path(@conn, :save_event, @event.id, action: "ignored"), method: :post, class: "action-btn left" %>
              <%= link "✓ Save", to: events_path(@conn, :save_event, @event.id, action: "added"), method: :post, class: "action-btn right" %>
          <% end %>
        <% else %>
          <%= case @saved_status do %>
            <% "added" -> %>
              <%= link "✗ Ignore", to: "#", class: "action-btn single disabled" %>
            <% "ignored" -> %>
              <%= link "✓ Save", to: "#", class: "action-btn single disabled" %>
            <% nil -> %>
              <%= link "✗ Ignore", to: "#", class: "action-btn left disabled" %>
              <%= link "✓ Save", to: "#", class: "action-btn right disabled" %>
          <% end %>
        <% end %>
      </div>
      <div>
    </div>
  </div>
</div>