web/router.ex
defmodule Eventrist.Router do
  use Eventrist.Web, :router
  import Eventrist.Session

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :user_data do
    plug :require_login
  end

  pipeline :feed do
    plug :accepts, ["text/calendar"]
  end

  scope "/", Eventrist do
    pipe_through :browser

    get  "/login",  RegistrationController, :login
    post "/login",  RegistrationController, :do_login
    get  "/signup", RegistrationController, :signup
    post "/signup", RegistrationController, :do_signup
    get  "/logout", RegistrationController, :logout

    get "/loaderio-88ec75cd570841f1ac0b26dfd6efbb93", LoaderioController, :verify

    # main page is info about the app
    get "/", RootController, :index
  end

  scope "/", Eventrist do
    pipe_through :feed
    get "/users/:user_id/feed.ical", FeedController, :feed
  end

  scope "/", Eventrist do
    pipe_through [:browser, :user_data]

    # Next recommended event for logged in user
    get "/events/next", EventsController, :next_event
    # Get all events that the logged in user has ignored
    get "/events/ignored", EventsController, :ignored
    # Save an event for the logged in user, either ignoring or adding it
    post "/events/:id/save", EventsController, :save_event
    # Get all events for the logged in user and show details about a specific event
    resources "/events", EventsController, only: [:index, :show]
  end

  defp require_login(conn, _) do
    case !logged_in?(conn) do
      true  -> redirect(conn, to: Eventrist.Router.Helpers.registration_path(conn, :login)) |> halt
      _     -> conn
    end
  end

  #pipeline :review_checks do
  #  plug :ensure_authenticated_user
  #  plug :ensure_user_owns_review
  #end
  #scope "/reviews", Eventrist do
  #  pipe_through :review_checks
  #  resources "reviews", ReviewController
  #end

  # see info for a particular user and see the events for that user
  #resources "users", UserController, only: [:show] do
  #  resources "events", EventsController, only: [:index, :create, :delete]
  #  resources "tags", TagsController, only: [:index]
  #end

  # see organisers and their events
  #resources "organisers", OrganisersController, only: [:index, :show] do
  #  resources "tags", TagsController, only: [:index]
  #  resources "events", EventsController, only: [:index]
  #end
end

web/views/layout_view.ex
defmodule Eventrist.LayoutView do
  use Eventrist.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="find tech events in Glasgow and Edinburgh">

    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#67A2D4">

    <title>Eventrist</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="https://cdn.jsdelivr.net/clipboard.js/1.5.3/clipboard.min.js"></script>
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <span class="header-title"><%= link "Eventrist", to: root_path(@conn, :index) %></span>
        <div class="nav pull-right">
          <%= if logged_in?(@conn) do %>
            <%= link "Recommended", to: events_path(@conn, :next_event) %>
            <%= link "Saved", to: events_path(@conn, :index) %>
            <%= link "Logout", to: registration_path(@conn, :logout) %>
          <% else %>
            <%= link "Login",    to: registration_path(@conn, :login) %>
            <%= link "Register", to: registration_path(@conn, :signup) %>
          <% end %>
        </div>
      </div>

      <div class="inner-content">
        <%= @inner %>
      </div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>